spring:
  datasource:
    url: jdbc:mysql://localhost:3306/querydsl
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        ddl-auto: none
        enable_lazy_load_no_trans: true
        jdbc.time_zone: UTC
        temp.use_jdbc_metadata_defaults: false

